version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gosec:
      excludes:
        - G104  # Covered by errcheck
        - G101  # False positives on URL constants and test fixtures
        - G115  # Integer overflow: bounded by constants
        - G304  # File paths from config/env, not user input
    misspell:
      locale: US
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"  # Disable stylecheck suggestions
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - vendor
